//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderPlacements.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "This field is required!")]
        public string first_name { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "This field is required!")]
        public string last_name { get; set; }

        [DisplayName("User Name")]
        [MinLength(6)]
        [Required(ErrorMessage = "This field is required!")]
        public string username { get; set; }

        [DisplayName("E-Mail")]
        [Required(ErrorMessage = "This field is required!")]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Please enter correct email")]
        public string email { get; set; }

        [DisplayName("Address")]
        [Required(ErrorMessage = "This field is required!")]
        public string address { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [MinLength(8)]
        [RegularExpression(@"(?=.*[A-Z])(?=.*[-+_!@#$%^&*., ?]).+", ErrorMessage = "Atleast a capital letter and special character should include")]
        [Required(ErrorMessage = "This field is required!")]
        public string password { get; set; }

        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "This field is required!")]
        [DataType(DataType.Password)]
        [MinLength(8)]
        [Compare("password")]
        public string ConfirmPassword { get; set; }

        [DisplayName("NIC")]
        [RegularExpression(@"[0-9]{9}V", ErrorMessage = "Please enter a correct NIC")]
        [Required(ErrorMessage = "This field is required!")]
        public string nic { get; set; }

        [DisplayName("Telephone/Mobile")]
        [RegularExpression(@"[0-9]{3}-?[0-9]{7}", ErrorMessage = "Please enter a correct Contact No")]
        [Required(ErrorMessage = "This field is required!")]
        public string telephone { get; set; }

        [DisplayName("Terms and Conditions")]
        [Required(ErrorMessage = "This field is required!")]
        public bool tandc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
