//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderPlacements.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class order
    {
        public int order_id { get; set; }
        public int customer_id { get; set; }

        [DisplayName("Package 01(LKR 250)")]
        public bool pack_one { get; set; }

        [DisplayName("Quantity")]
        public Nullable<decimal> pack_one_quantity { get; set; }

        [DisplayName("Package 02(LKR 350)")]
        public bool pack_two { get; set; }

        [DisplayName("Quantity")]
        public Nullable<decimal> pack_two_quantity { get; set; }

        [DisplayName("Package 03(LKR 500)")]
        public bool pack_three { get; set; }

        [DisplayName("Quantity")]
        public Nullable<decimal> pack_three_quantity { get; set; }

        [DisplayName("Total")]
        public Nullable<decimal> total { get; set; }
        public string status { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
